spring.application.name=blog-backend
server.port=8080

spring.datasource.url=jdbc:h2:file:./data/blogdb;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.jackson.serialization.write-dates-as-timestamps=false

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

blog.admin.username=admin
blog.admin.password-hash=f3b036d9b824fd850dc29e10970047bbccf0f51288281d10236b91071bef9185
blog.admin.salt=ea7ff2f70913143a35a5537c2f2dc3f8