spring.application.name=blog-backend
server.port=8080

spring.datasource.url=jdbc:h2:file:./data/blogdb;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.jackson.serialization.write-dates-as-timestamps=false

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

blog.admin.username=admin
blog.admin.password-hash=793bcee5edd5045b87f5c2dbf55b1bf1e310de44bf3248a6db9e96b1e58e8b13
blog.admin.salt=4a7d1ed8c3f54062b82e9aa13cde650f